### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ghost** [Botrixlist/botrix#35]
SyntaxError: /home/runner/upcord-1/src/config.json: Unexpected token ] in JSON at position 239
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1111:22)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/upcord-1/src/routes/api/bots/submit.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/upcord-1/src/routes/api/routes/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
<img width="583" alt="Screen Shot 2021-06-09 at 4 23 42 pm" src="https://user-images.githubusercontent.com/77712352/121304001-1a855380-c93f-11eb-809e-a38e1d32732a.png">

**Comment by dylanjamesdev** [comment]
Run the json file through a json linter to solve the issue.
