### ISSUE TITLE
Bug:Error When Running

### ISSUE THREAD

**Issue by WaltDisneyWorld** [Botrixlist/botrix#6]
I'm getting an error when trying to run it:
```SyntaxError: /home/runner/botrix/src/config.json: Unexpected token / in JSON at position 570
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/botrix/src/routes/api/bots/submit.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/botrix/src/routes/api/routes/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)```

**Comment by WindowsCmd** [comment]
Hi, Have you ran `npm i` ? It seems as if you are missing some dependencies

**Comment by WaltDisneyWorld** [comment]
I did.

**Comment by WindowsCmd** [comment]
It also seems like you have not provided the entire error message, please provide the entire error message.

**Comment by WaltDisneyWorld** [comment]
``` npm start

> botrix-rewrite@1.0.0 start /home/runner/botrix
> node src/index.js

internal/modules/cjs/loader.js:1174
    throw err;
    ^

SyntaxError: /home/runner/botrix/src/config.json: Unexpected token / in JSON at position 570
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/botrix/src/routes/api/bots/submit.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/botrix/src/routes/api/routes/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botrix-rewrite@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the botrix-rewrite@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-01-04T14_59_54_801Z-debug.log
exit status 1
 ```

**Comment by WindowsCmd** [comment]
Okay, It seems as there is a problem with your config file.. Could you provide your config.json file for me?

**Comment by WaltDisneyWorld** [comment]
Can I share it privately?

**Comment by WaltDisneyWorld** [comment]
https://repl.it/join/kzzkhxzx-discordapp

**Comment by WaltDisneyWorld** [comment]
Join and look at config.

**Comment by WindowsCmd** [comment]
It seems like the comments were messing with the json syntax.

**Comment by WaltDisneyWorld** [comment]
What should I do?

**Comment by dylanjamesdev** [comment]
Learn JSON or use a json linter.
